/**
 * LT-AUTOCAPTION unit tests.
 *
 * Verifies that cues generated by the transcription service (containing
 * timestamps, text, and per-word timing) pass through subtitleCuesToLayers
 * unchanged, generating valid MotionLayers with correct visibility windows.
 */

import { describe, it, expect } from "vitest";
import type { SubtitleCue } from "../../types/subtitle";
import { getPreset } from "../../subtitle/presets";
import { subtitleCuesToLayers } from "../subtitles/subtitleLayers";

const SCENE = { sceneWidth: 1920, sceneHeight: 1080, sceneDurationMs: 10000 };

describe("LT-AUTOCAPTION cue pipeline", () => {
  it("converts transcription SubtitleCue[] into text layers with word mode 'line'", () => {
    const transcribedCues: SubtitleCue[] = [
      {
        id: "cue-1",
        start: 0.5,
        end: 2.0,
        text: "Auto generated caption line 1",
        words: [
          { text: "Auto", start: 0.5, end: 0.8 },
          { text: "generated", start: 0.9, end: 1.4 },
          { text: "caption", start: 1.5, end: 1.8 },
          { text: "line 1", start: 1.8, end: 2.0 },
        ],
      },
      {
        id: "cue-2",
        start: 2.5,
        end: 4.0,
        text: "Auto generated caption line 2",
        words: [
          { text: "Auto", start: 2.5, end: 2.8 },
          { text: "generated", start: 2.9, end: 3.4 },
          { text: "caption", start: 3.5, end: 3.8 },
          { text: "line 2", start: 3.8, end: 4.0 },
        ],
      },
    ];

    const result = subtitleCuesToLayers(transcribedCues, {
      style: getPreset("classic"),
      ...SCENE,
    });

    expect(result.droppedCueCount).toBe(0);
    expect(result.layers.length).toBe(2);
    expect(result.layers[0].visible_start_ms).toBe(500);
    expect(result.layers[0].visible_end_ms).toBe(2000);
    expect(result.layers[0].text?.text).toBe("Auto generated caption line 1");
    expect(result.layers[1].visible_start_ms).toBe(2500);
    expect(result.layers[1].visible_end_ms).toBe(4000);
    expect(result.layers[1].text?.text).toBe("Auto generated caption line 2");
  });

  it("converts transcription SubtitleCue[] into word layers with word mode 'word_pop'", () => {
    const transcribedCues: SubtitleCue[] = [
      {
        id: "cue-1",
        start: 1.0,
        end: 2.0,
        text: "Hello world",
        words: [
          { text: "Hello", start: 1.0, end: 1.4 },
          { text: "world", start: 1.5, end: 2.0 },
        ],
      },
    ];

    const result = subtitleCuesToLayers(transcribedCues, {
      style: getPreset("word_pop"),
      ...SCENE,
    });

    expect(result.layers.length).toBe(2);
    expect(result.layers[0].text?.text).toBe("Hello");
    expect(result.layers[0].visible_start_ms).toBe(1000);
    expect(result.layers[0].visible_end_ms).toBe(1400);
    expect(result.layers[1].text?.text).toBe("world");
    expect(result.layers[1].visible_start_ms).toBe(1500);
    expect(result.layers[1].visible_end_ms).toBe(2000);
  });
});
